apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: tenant-wordpress
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "6"
    limits.memory: 8Gi
    pods: "20"
    persistentvolumeclaims: "6"
    services: "10"
    services.loadbalancers: "0"
    services.nodeports: "0"
